### ISSUE TITLE
Assistance Required with ChromaDB Plugin Installation on Windows

### ISSUE THREAD

**Issue by kruzea22** [BBC-Esq/VectorDB-Plugin#121]
Windows 11 Platform Issue:

Initial steps including document loading, processing, and embedding model loading proceed without issue.
However, upon attempting to create the database, the process is interrupted with a traceback error indicating a deprecated configuration of Chroma is being used.

The specific error encountered on the Windows 11 platform is as follows:

database_interactions.py: Successfully loaded documents.
document_processor.py: Splitting documents.
document_processor.py: Number of Chunks: 3
document_processor.py: Chunks between 1 and 100 characters: 3
database_interactions.py: Creating embeddings.
sentence_transformers.SentenceTransformer - C:\Users\Dealer\downloads\lm\src\Lib\site-packages\sentence_transformers\SentenceTransformer.py:110 - __init__
C:\Users\Dealer\downloads\lm\src\Lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly. To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
   return self.fget.__get__(instance, owner)()
database_interactions.py: Embedding model loaded.
database_interactions.py: Creating database.
Traceback (most recent call last):
   File "C:\Users\Dealer\downloads\lm\src\gui_tabs_databases.py", line 16, in run
     create_vector_db.run()
   File "C:\Users\Dealer\downloads\lm\src\database_interactions.py", line 59, in run
     db = Chroma.from_documents(
          ^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\langchain_community\vectorstores\chroma.py", line 778, in from_documents
     return cls.from_texts(
            ^^^^^^^^^^^^^^^
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\langchain_community\vectorstores\chroma.py", line 714, in from_texts
     chroma_collection = cls(
                         ^^^^
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\langchain_community\vectorstores\chroma.py", line 120, in __init__
     self._client = chromadb.Client(_client_settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\chromadb\__init__.py", line 248, in Client
     return ClientCreator(tenant=tenant, database=database, settings=settings)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\chromadb\api\client.py", line 139, in __init__
     super().__init__(settings=settings)
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\chromadb\api\client.py", line 43, in __init__
     SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\chromadb\api\client.py", line 50, in _create_system_if_not_exists
     new_system = System(settings)
                  ^^^^^^^^^^^^^^^^
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\chromadb\config.py", line 313, in __init__
     if settings[key] is not None:
        ~~~~~~~~^^^^^
   File "C:\Users\Dealer\downloads\lm\src\Lib\site-packages\chromadb\config.py", line 250, in __getitem__
     raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
______________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!

**Comment by BBC-Esq** [comment]
run ```pip show chromadb``` and see which version of chromadb is installed.  It must be the version within my ```requirements.txt``` file.  I believe that'll solve the issue.

**Comment by kruzea22** [comment]
thanks

then i did
python -m venv env
.\env\Scripts\activate
pip install -r requirements.txt

and it is all fine

(env) PS C:\Users\Dealer\downloads\lm\src> py gui.py
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
doh set to ""  --  SystemOnly
QPainter::end: Painter ended with 4 saved states
QPainter::end: Painter ended with 4 saved states
QPainter::end: Painter ended with 4 saved states
QPainter::end: Painter ended with 4 saved states
QPainter::end: Painter ended with 4 saved states
QPainter::end: Painter ended with 4 saved states
QPainter::end: Painter ended with 4 saved states
database_interactions.py: Loading documents.
document_processor.py: Number of workers assigned: 3
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
document_processor.py: Number of NON-IMAGE files loaded: 1
document_processor.py: Number of NON-IMAGE files loaded: 2
document_processor.py: Number of NON-IMAGE files loaded: 3
document_processor.py: Loading images, if any.
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
No files detected in the 'Images_for_DB' directory.
database_interactions.py: Successfully loaded documents.
document_processor.py: Splitting documents.
document_processor.py: Number of Chunks: 3
document_processor.py: Chunks between 1 and 100 characters: 3
database_interactions.py: Creating embeddings.
sentence_transformers.SentenceTransformer - C:\Users\Dealer\downloads\lm\src\env\Lib\site-packages\sentence_transformers\SentenceTransformer.py:66 - __init__
database_interactions.py: Embedding model loaded.
database_interactions.py: Creating database.
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.71it/s]
database_interactions.py: Persisting database.
database_interactions.py: Database persisted.
database_interactions.py: Embedding model removed from memory.
